version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      - MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{‌{ checksum "pom.xml" }}
            - v1-dependencies-

      # Forces maven to download everything
      # Will install the modules into the local maven cache
      # It will skip the test till it gets to runing integration-test
      # Because we have one module dependant on another we need to perform the build this way
      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{‌{ checksum "pom.xml" }}

      - run: mvn integration-test
