version: 2
jobs:
  build:
    working_directory: ~/Recipe
    docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
    - checkout
    - restore_cache:
        key: Recipe-{{ checksum "pom.xml" }}
    - run: mvn install -DskipTests
    - run: mvn dependency:go-offline
    - save_cache:
        key: Recipe-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
  test:
    docker:
    - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
    - checkout
    - run: mvn package
    - store_test_results: 
      path: target/surefire-reports
    - store_artifacts:
        path: target/Recipe-0.0.1-SNAPSHOT.jar
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
